/** Idempotent seed definitions for migrate-trend-definitions.js (44 panels). */

function ms(patterns, labels = [], colors = []) {
  return patterns.map((keyPattern, i) => ({
    key: '',
    keyPattern,
    label: labels[i] || '',
    color: colors[i] || '',
    aggregation: 'avg',
  }));
}

const REPORTS_TRENDS = [
  {
    panelId: 'plant_load_gauge',
    title: 'Plant load vs period avg',
    category: 'energy',
    chartType: 'gauge',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 1,
    maxKeys: 1,
    metricSeries: ms(['total_plant_load|plant_total_load']),
  },
  {
    panelId: 'plant_load',
    title: 'Plant load (MW)',
    category: 'energy',
    chartType: 'composed',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 2,
    metricSeries: ms(['total_plant_load|plant_total_load']),
  },
  {
    panelId: 'sw_balance',
    title: 'Seawater production vs consumption',
    category: 'water',
    chartType: 'line',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 3,
    metricSeries: ms(['sw.*prod|total_sw_prod', 'sw.*cons|total_sw_cons']),
  },
  {
    panelId: 'dm_balance',
    title: 'Demin water production vs consumption',
    category: 'water',
    chartType: 'line',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 4,
    metricSeries: ms(['dm.*prod|total_dm_prod', 'dm.*cons|total_dm_cons']),
  },
  {
    panelId: 'tank_levels',
    title: 'Tank levels',
    category: 'water',
    chartType: 'area',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 5,
    metricSeries: ms(['tank|st-?\\d|dt-?\\d|level']),
  },
  {
    panelId: 'fuel_gas',
    title: 'Fuel gas (tons)',
    category: 'energy',
    chartType: 'bar',
    unit: 'T',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 6,
    metricSeries: ms(['daily_op_fuel_gas|plant_fuel_gas|(?:^|_)fuel_gas(?!.*col_)']),
  },
  {
    panelId: 'chemistry',
    title: 'Chemistry & RO',
    category: 'chemistry',
    chartType: 'line',
    dataSource: 'chemistry_water',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 7,
    maxKeys: 6,
    metricSeries: ms(['^ro_', '^hrsg_']),
  },
  {
    panelId: 'environment',
    title: 'Environmental',
    category: 'environment',
    chartType: 'area',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 8,
    metricSeries: ms(['emission|stack|nox|so2|co2|ambient|environment']),
  },
  {
    panelId: 'power_gen',
    title: 'Power generation',
    category: 'energy',
    chartType: 'line',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 9,
    metricSeries: ms([
      '^(?:plant_)?gross_generation|^(?:plant_)?net_generation|power_generation|plant_generation',
    ]),
  },
  {
    panelId: 'power_kpi',
    title: 'GT power vs period avg',
    category: 'shift',
    chartType: 'kpi',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 10,
    maxKeys: 1,
    metricSeries: ms(['power_mw|shift.*power']),
  },
  {
    panelId: 'shift_power',
    title: 'Shift report — GT power',
    category: 'shift',
    chartType: 'line',
    showOnTrends: true,
    appliesToRoutes: ['/reports/trends'],
    order: 11,
    maxKeys: 6,
    metricSeries: ms(['power_mw|shift.*power']),
  },
];

const HOME_INSIGHT = [
  { suffix: 'gn', title: 'Generation', patterns: ['daily_op_plant_gross_gen|plant_generation|gross.*gen|generation'] },
  { suffix: 'ld', title: 'Load MW', patterns: ['daily_op_total_plant_load|plant_total_load|total_plant_load|load_mw'] },
  { suffix: 'pf', title: 'PLF %', patterns: ['daily_op_plf|plf|plant.*availability'] },
  { suffix: 'ef', title: 'Efficiency %', patterns: ['daily_op_net_efficiency|plant_net_efficiency|net_efficiency'] },
  { suffix: 'hr', title: 'Heat Rate', patterns: ['daily_op_heat_rate|plant_heat_rate|heat_rate'] },
  { suffix: 'fu', title: 'Fuel Gas', patterns: ['daily_op_fuel_gas|plant_fuel_gas|fuel_gas'] },
  { suffix: 'mf', title: 'MFEQH', patterns: ['mfeqh|equivalent.*operating'] },
  { suffix: 'nox', title: 'NOx', patterns: ['nox|no_x'] },
  { suffix: 'sox', title: 'SOx', patterns: ['sox|so2|sulphur'] },
  { suffix: 'co', title: 'CO', patterns: ['\\bco\\b|carbon monoxide'] },
].map((row, i) => ({
  panelId: `home_insight_${row.suffix}`,
  title: row.title,
  category: 'energy',
  chartType: 'kpi',
  showOnInsightStrip: true,
  showOnHome: true,
  appliesToRoutes: ['/'],
  order: 100 + i,
  maxKeys: 1,
  metricSeries: ms(row.patterns),
}));

const HOME_KPI = [
  { suffix: 'gn', patterns: ['daily_op_plant_gross_gen|generation|gross_generation|plant_generation'] },
  { suffix: 'ld', patterns: ['daily_op_total_plant_load|load|plant_load|load_mw'] },
  { suffix: 'pf', patterns: ['daily_op_plf|plf|plant_load_factor'] },
  { suffix: 'ef', patterns: ['daily_op_net_efficiency|efficiency|net_efficiency'] },
  { suffix: 'hr', patterns: ['daily_op_heat_rate|heat_rate|heatrate'] },
  { suffix: 'fu', patterns: ['daily_op_fuel_gas|fuel|fuel_gas'] },
].map((row, i) => ({
  panelId: `home_kpi_${row.suffix}`,
  title: `Home KPI ${row.suffix.toUpperCase()}`,
  category: 'energy',
  chartType: 'kpi',
  showOnHome: true,
  appliesToRoutes: ['/'],
  order: 200 + i,
  maxKeys: 2,
  metricSeries: ms(row.patterns),
}));

const HOME_CHARTS = [
  { id: 'cT', title: 'Combined trend', patterns: ['daily_op_plant_gross_gen|daily_op_total_plant_load|daily_op_plf|daily_op_net_efficiency|daily_op_heat_rate|daily_op_fuel_gas|generation|load|plf|efficiency|heat_rate|fuel|mfeqh'] },
  { id: 'cHR', title: 'Heat rate chart', patterns: ['daily_op_heat_rate|heat_rate|heatrate'] },
  { id: 'cEF', title: 'Efficiency chart', patterns: ['daily_op_net_efficiency|efficiency|net_efficiency'] },
  { id: 'cPF', title: 'PLF chart', patterns: ['daily_op_plf|plf|plant_load_factor'] },
  { id: 'cMF', title: 'MFEQH chart', patterns: ['daily_op_.*_mfeqh|mfeqh'] },
  { id: 'cEM', title: 'Emissions chart', patterns: ['nox|sox|so2|co|emissions'] },
  { id: 'cFU', title: 'Fuel chart', patterns: ['daily_op_fuel_gas|fuel|fuel_gas'] },
  { id: 'cUN', title: 'Water chart', patterns: ['water|makeup_water|daily_op_.*_mwh'] },
].map((row, i) => ({
  panelId: `home_chart_${row.id}`,
  title: row.title,
  category: 'energy',
  chartType: 'line',
  showOnHome: true,
  appliesToRoutes: ['/'],
  order: 300 + i,
  metricSeries: ms(row.patterns),
}));

const HOME_CHEM = [
  {
    panelId: 'home_chem_ro',
    title: 'RO chemistry',
    category: 'chemistry',
    dataSource: 'chemistry_water',
    chartType: 'line',
    showOnHome: true,
    appliesToRoutes: ['/'],
    order: 400,
    metricSeries: ms(['ro|permeate|recovery']),
  },
  {
    panelId: 'home_chem_hrsg',
    title: 'HRSG chemistry',
    category: 'chemistry',
    dataSource: 'chemistry_water',
    chartType: 'line',
    showOnHome: true,
    appliesToRoutes: ['/'],
    order: 401,
    metricSeries: ms(['hrsg|conductivity|silica']),
  },
  {
    panelId: 'home_chem_water',
    title: 'Water balance',
    category: 'water',
    dataSource: 'chemistry_water',
    chartType: 'line',
    showOnHome: true,
    appliesToRoutes: ['/'],
    order: 402,
    metricSeries: ms(['water|dm|sw|consumption']),
  },
];

const MANAGEMENT = [
  {
    panelId: 'management_monthly_generation',
    title: 'Monthly generation',
    category: 'energy',
    chartType: 'bar',
    showOnManagement: true,
    appliesToRoutes: ['/management'],
    monthlyAggregation: 'sum',
    order: 500,
    metricSeries: ms(['plant_generation|gross.*gen|generation']),
  },
  {
    panelId: 'management_monthly_plf',
    title: 'Monthly PLF',
    category: 'energy',
    chartType: 'line',
    showOnManagement: true,
    appliesToRoutes: ['/management'],
    monthlyAggregation: 'avg',
    order: 501,
    metricSeries: ms(['plf|plant.*availability']),
  },
  {
    panelId: 'management_kpi_plf',
    title: 'Management PLF KPI',
    category: 'energy',
    chartType: 'kpi',
    showOnManagement: true,
    appliesToRoutes: ['/management'],
    order: 502,
    metricSeries: ms(['plf']),
  },
  {
    panelId: 'management_kpi_hr',
    title: 'Management heat rate KPI',
    category: 'energy',
    chartType: 'kpi',
    showOnManagement: true,
    appliesToRoutes: ['/management'],
    order: 503,
    metricSeries: ms(['heat_rate']),
  },
  {
    panelId: 'management_kpi_fu',
    title: 'Management fuel KPI',
    category: 'energy',
    chartType: 'kpi',
    showOnManagement: true,
    appliesToRoutes: ['/management'],
    order: 504,
    metricSeries: ms(['fuel_gas|fuel']),
  },
  {
    panelId: 'management_kpi_gn',
    title: 'Management generation KPI',
    category: 'energy',
    chartType: 'kpi',
    showOnManagement: true,
    appliesToRoutes: ['/management'],
    order: 505,
    metricSeries: ms(['plant_generation|generation']),
  },
];

const TREND_DEFINITION_SEEDS = [
  ...REPORTS_TRENDS,
  ...HOME_INSIGHT,
  ...HOME_KPI,
  ...HOME_CHARTS,
  ...HOME_CHEM,
  ...MANAGEMENT,
];

module.exports = { TREND_DEFINITION_SEEDS };
